site_name: Ara Imgui documentation
site_url: https://hanamileh.github.io/ara_imgui/
theme:
  name: material
nav:
  - Main: index.md
  - Cheat sheet: cheat_sheet.md
  - Widgets:
      - Text: widgets/text.md
      - Button: widgets/button.md
      - Radio Button: widgets/radio_button.md
      - Checkbox: widgets/checkbox.md
      - Separator: widgets/separator.md
      - Input Float: widgets/input_float.md
      - Input Int: widgets/input_int.md
      - Text colored: widgets/text_colored.md
      - Text disabled: widgets/text_disabled.md
      - Text wrapped: widgets/text_wrapped.md
      - Text link: widgets/text_link.md
      - Text link open url: widgets/text_link_open_url.md